layout_spectrum: 1
typography_spectrum: 1
color:
  saturation: 0.5904462
  lightness: 0.7060006
  brandStrength: 0.2912271
  rhythmicContrast: 0.912494
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Robert Johnson
